sudo: required
services:
  - docker

before_install:
  - docker build -t mytag -f Dokerfile.dev .
script:
  - docker run -e CI=true mytag npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket: "elasticbeanstalk-eu-west-1-298563229358"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "AWS_SECRET_KEY"



